### ISSUE TITLE
新版本部署了，无法注册，后端无法打开

### ISSUE THREAD

**Issue by b2522** [Symph0nia/CyberEdge#25]
新版本部署了，各容器均已正常运行，无法注册，后端无法打开，帮忙看一下。

![image](https://github.com/user-attachments/assets/ecd9f180-9438-4b6c-b7de-538420a52faf)
![image](https://github.com/user-attachments/assets/5155b367-2b74-41de-ac41-49029eb6c471)

**Comment by ZacharyZcR** [comment]
您好，如果使用本地二进制文件搭建的方式，请注意运行时使用./cyberedge -env prod，该问题可能是由于同源问题产生的，如果以上修复无效，请提供一下前端访问后端的F12浏览器控制台网络信息截图。

**Comment by b2522** [comment]
使用的是./start.sh部署的，容器都正常运行
![image](https://github.com/user-attachments/assets/4058d915-4387-4c30-a0f0-87718f56a78c)

注册的时候无法生成二维码，看日志是这个错误
![image](https://github.com/user-attachments/assets/7d48edb4-936b-4ca2-8e60-8cf152203628)

后端无法打开，浏览器F12截图
![image](https://github.com/user-attachments/assets/e0045954-be58-489a-913f-e6a2725e53c8)

**Comment by ZacharyZcR** [comment]
目前没有在Windows和Mac ARM 版本上复现该问题，请您提供更多系统版本信息以供我们本地测试，感觉可能是架构问题

**Comment by b2522** [comment]
我用的是一台INTEL N5105的小主机里的安装的ubuntu虚拟机，amd_X64架构的cpu

**Comment by ZacharyZcR** [comment]
应该是MongoDB版本的问题，我写了一份低版本（4.0以下）的docker-compose.yaml，请你替换后尝试一下。

```yaml
version: '3'

services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:

   - "31337:31337"
     vironment:
        - MONGODB_URI=mongodb://mongodb:27017
          REDIS_ADDR=redis:6379
              volumes:
             - ./.env:/app/.env
               pends_on:
                  - mongodb
                    redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "47808:47808"
    depends_on:
      - backend

volumes:
  mongodb_data:
  redis_data:
```
